# Generated by Django 5.2.7 on 2025-10-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('specialty', models.CharField(max_length=200, verbose_name='Специализация')),
                ('bio', models.TextField(verbose_name='Биография')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coaches/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
    ]
