# Generated by Django 5.2.7 on 2025-10-27 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_newsitem_image_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='image_news',
            field=models.ImageField(blank=True, null=True, upload_to='media/news', verbose_name='Фото для новости'),
        ),
    ]
