# Generated by Django 5.2.7 on 2025-10-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactinfo',
            name='vk_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Ссылка на ВК'),
        ),
    ]
