# Generated by Django 5.2.7 on 2025-10-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='image_news',
            field=models.ImageField(blank=True, null=True, upload_to='staticfiles/coach', verbose_name='Фото для новости'),
        ),
    ]
